---
- hosts: app_server
  tasks:
    - name: Adding repository for node
      become: yes
      yum_repository:
        name: nodejs
        description: Node YUM repo
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        state: present
        gpgcheck: no

    - name: Installing nodejs
      become: yes
      yum:
        name: nodejs
        state: latest

    - name: Installing 'Development tools' package group
      become: yes
      yum:
        name: "@Development tools"
        state: present

    - name: Installing openssl-devel
      become: yes
      yum:
        name: openssl-devel

    - unarchive:
        src: http://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz
        dest: ./
        remote_src: true

    - name: Configure ruby installation
      shell: ./configure --prefix=/home/vagrant
      args:
        chdir: ruby-2.4.0/

    - name: Create make file
      shell: make
      args:
        chdir: ruby-2.4.0/

    - name: Make install ruby
      shell: make install
      args:
        chdir: ruby-2.4.0/

    - name: Adding repository for postgres
      become: yes
      yum_repository:
        name: postgres
        description: Postgres YUM repo
        baseurl: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6.7-x86_64
        state: present
        gpgcheck: no

    - name: Install postgresql packages
      become: yes
      yum: name={{ item }} state=present
      with_items:
        - postgresql96
        - postgresql96-server
        - postgresql96-devel
        - python-psycopg2

    - name: Init db
      become: yes
      shell: service postgresql-9.6 initdb

    - name: Starting service
      become: yes
      service: name=postgresql-9.6
               state=restarted


    - name: Create vagrant user
      become: yes
      become_user: postgres
      postgresql_user: name=vagrant

    - name: Ensure user does not have unnecessary privilege
      become: yes
      become_user: postgres
      postgresql_user: name=vagrant role_attr_flags=SUPERUSER,CREATEDB,REPLICATION

    - name: Ensure user does not have unnecessary privilege
      become: yes
      become_user: postgres
      postgresql_db: db=tweetable_development

    - name: Ensure user does not have unnecessary privilege
      become: yes
      become_user: postgres
      postgresql_db: db=tweetable_test

